### ISSUE TITLE
[Feature Request] Module to enable the WebService Rest API

### ISSUE THREAD

**Issue by xenlo** [HewlettPackard/hpe3par_ansible_module#53]
**Summary**
Up to now, the `hpe3par_*` modules have as prerequisite to have the WebService Rest API started, which is not the case by default. It could be great to have a module that enables the service for us. 

**UseCase**
Provisioning of HPe 3PAR from bare-metal.

**Current Implementation**
With a quite ugly workaround, I'm able to ensure that the Rest API will be accessible before using my playbooks with the `hpe3par_*`_ modules. But it's a pain with because the password can't be managed properly and in plus is based on a tasks with `command` module that should be avoid.
```
---
- name: Prepare the SAN HPe 3PAR
  hosts: localhost
  gather_facts: no

  vars:
    hpe3par_user: "user"
    hpe3par_ip: "10.0.0.1"
	
  tasks:
    - name: Ensure that the WebService API is enabled
      command: >
        ssh -oStrictHostKeyChecking=no {{ hpe3par_user }}@{{ hpe3par_ip }} startwsapi

    - name: Wait for the WebService API to be started
      wait_for:
        host: "{{ hpe3par_ip }}"
        port: 8080
        state: started
```
